[workspace]
authors = ["Giordon Stark <kratsg@gmail.com>"]
channels = ["conda-forge"]
name = "af-docs"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[dependencies]
python = ">=3.14.0,<3.15"
pre-commit = ">=4.5.1,<5"
zensical = "*"
lychee = "*"
pydocstyle = "*"
beautifulsoup4 = ">=4.14.3,<5"

[tasks]
build = { cmd = "zensical build", description = "Build documentation (static)", inputs = ["src/", "docs/", "zensical.toml"], outputs = ["site"] }
serve = { cmd = "zensical serve", depends-on = ["build"], description = "Build and serve documentation" }
validate = { cmd = "lychee docs/", description = "Check documentation for broken links" }
build-check = { depends-on = ["build", "validate"] }
clean = { cmd = "rm -rf site", description = "Clean documentation build artifacts", inputs = ["site"] }
extract-text = { cmd = "python extract_site_text.py", depends-on = ["build"] }
